badges/urls.py
from django.urls import re_path

from badges.views import OwnBadge, CheckInBadgeView

urlpatterns = [
    re_path(r'^$', OwnBadge.as_view(),
        name='badges.own'),
    re_path(r'^check_in/(?P<username>[\w.@+-]+)/$', CheckInBadgeView.as_view(),
        name='badges.check_in'),
]

debconf/urls.py
from django.urls import re_path
from django.views.generic import RedirectView

from debconf.views import (
    ContentStatisticsView, DebConfScheduleView, IndexView,
    RobotsView, StatisticsView, now_or_next,
)

urlpatterns = [
    re_path(r'^favicon.ico$', RedirectView.as_view(url="/static/img/favicon.ico", permanent=True)),
    re_path(r'^schedule/$', DebConfScheduleView.as_view(),
        name='wafer_full_schedule'),
    re_path(r'^now_or_next/(?P<venue_id>\d+)/$', now_or_next, name="now_or_next"),
    re_path(r'^robots.txt$', RobotsView.as_view()),
    re_path(r'^$', IndexView.as_view()),
    re_path(r'^statistics/$', StatisticsView.as_view()),
    re_path(r'^talks/statistics/$', ContentStatisticsView.as_view(),
        name='content-statistics'),
]

invoices/urls.py
from django.urls import re_path

from invoices.views import (
    InvoiceCancel, InvoiceCombine, InvoiceDisplay, stripe_webhook)

app_name = 'invoices'
urlpatterns = [
    re_path(r'^combine/$', InvoiceCombine.as_view(), name='combine'),
    re_path(r'^stripe-webhook/$', stripe_webhook),
    re_path(r'^(?P<reference_number>[^/]+)/$', InvoiceDisplay.as_view(),
        name='display'),
    re_path(r'^(?P<reference_number>[^/]+)/cancel/$', InvoiceCancel.as_view(),
        name='cancel'),
]

minidebconf/urls.py
from django.conf.urls import include
from django.urls import re_path
from minidebconf.views import RegisterView, UnregisterView, RegistrationFinishedView

urlpatterns = [
    re_path(r'^register/$', RegisterView.as_view(), name='register'),
    re_path(r'^unregister/$', UnregisterView.as_view(), name='unregister'),
    re_path(r'^register/finished/$', RegistrationFinishedView.as_view(), name='registration_finished'),
    re_path(r'', include('debconf.urls')),
    re_path(r'', include('wafer.urls')),
]

invoices/forms.py
from django import forms
from django.core.signing import BadSignature

from crispy_forms.helper import FormHelper

from invoices.models import Invoice


class InvoiceForm(forms.Form):
    url = forms.URLField(
        label='URL',
        required=False,
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.include_media = False

    def clean_url(self):
        url = self.cleaned_data['url']
        invalid_url_error = 'Needs to a be a valid URL for a visible invoice'

        # The URL validator should have ensured that we have enough slashes to
        # do things like this
        reference_number = url.rstrip('/').rsplit('/', 1)[1]
        signed_url = ':' in reference_number
        if signed_url:
            try:
                reference_number = Invoice.signer.unsign(reference_number)
            except BadSignature:
                raise forms.ValidationError(invalid_url_error)

        try:
            invoice = Invoice.objects.get(reference_number=reference_number)
        except Invoice.DoesNotExist:
            raise forms.ValidationError(invalid_url_error)

        if self.user != invoice.recipient and not signed_url:
            raise forms.ValidationError(invalid_url_error)

        if invoice.status != 'new':
            raise forms.ValidationError('Invoice is not unpaid')

        if invoice.compound:
            raise forms.ValidationError('This is a combined invoice, itself')

        self.invoice = invoice

        return url


class InvoiceFormset(forms.BaseFormSet):
    def clean(self):
        if any(self.errors):
            return

        invoices = []
        for form in self.forms:
            if hasattr(form, 'invoice'):
                invoices.append(form.invoice.pk)

        if len(invoices) > len(set(invoices)):
            raise forms.ValidationError('Invoices must be distinct')

        if len(invoices) < 2:
            raise forms.ValidationError(
                'At least 2 URLs need to be provided for any combining to '
                'happen.')


class CombineForm(forms.Form):
    invoiced_entity = forms.CharField(
        label='Invoiced entity',
    )
    billing_address = forms.CharField(
        label='Billing address',
        widget=forms.Textarea(attrs={'rows': 3}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.include_media = False

invoices/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.signing import BadSignature
from django.db import transaction
from django.forms.models import formset_factory
from django.http import (
    Http404, HttpResponse, HttpResponseBadRequest, HttpResponseRedirect)
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, TemplateView

from wafer.registration.views import redirect_profile

from stripe import Webhook
from stripe.error import AuthenticationError, SignatureVerificationError

from invoices.forms import CombineForm, InvoiceForm, InvoiceFormset
from invoices.models import Invoice, InvoiceLine
from invoices.stripe_payments import (
    charge_refunded, dispute_filed, payment_intent_succeeded)
from register.models import Attendee

log = logging.getLogger(__name__)


class InvoiceDetailView(DetailView):
    model = Invoice
    slug_field = 'reference_number'
    slug_url_kwarg = 'reference_number'

    def get_object(self):
        invoice = super().get_object()

        if self.can_view_invoice(invoice):
            return invoice

        raise Http404()

    def can_view_invoice(self, invoice):
        user = self.request.user
        return (user.has_perm('front_desk.change_checkin')
                or invoice.recipient == user)

    def can_cancel_invoice(self, invoice):
        user = self.request.user
        return (user.has_perm('front_desk.change_invoice')
                or invoice.recipient == user)


class InvoiceDisplay(InvoiceDetailView):
    template_name = 'invoices/invoice_detail.html'

    def get_object(self):
        self.unsign()
        return super().get_object()

    def unsign(self):
        reference_number = self.kwargs['reference_number']
        self.using_signed_url = ':' in reference_number
        if self.using_signed_url:
            try:
                reference_number = Invoice.signer.unsign(reference_number)
            except BadSignature:
                raise Http404()
            self.kwargs['reference_number'] = reference_number

    def can_view_invoice(self, invoice):
        return self.using_signed_url or super().can_view_invoice(invoice)

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        if self.object.status == 'new':
            try:
                payment_intent = self.object.get_payment_intent()
                payment_intent_client_secret = payment_intent.client_secret
            except AuthenticationError:
                log.error('Stripe authentication error. '
                          'Is STRIPE_ENDPOINT_SECRET set?')
                payment_intent_client_secret = ''

            context_data.update({
                'payment_intent_client_secret': payment_intent_client_secret,
                'STRIPE_PUBLISHABLE_KEY': settings.STRIPE_PUBLISHABLE_KEY,
            })

        context_data.update({
            'using_signed_url': self.using_signed_url,
            'DEBCONF_BILLING_CURRENCY': settings.DEBCONF_BILLING_CURRENCY,
            'DEBCONF_CITY': settings.DEBCONF_CITY,
            'DEBCONF_LOCAL_CURRENCY': settings.DEBCONF_LOCAL_CURRENCY,
            'DEBCONF_NAME': settings.DEBCONF_NAME,
            'DEBCONF_INVOICE_ADDRESS': settings.DEBCONF_INVOICE_ADDRESS,
        })

        return context_data


class InvoiceCancel(LoginRequiredMixin, InvoiceDetailView):

    @transaction.atomic
    def post(self, request, **kwargs):
        invoice = self.get_object()
        if not self.can_cancel_invoice(invoice):
            raise PermissionDenied()

        if invoice.status == 'new':
            invoice.status = 'canceled'
            invoice.save()
            messages.success(
                self.request, 'Invoice cancelled')
        else:
            messages.warning(
                self.request, 'Only unpaid invoices can be cancelled')

        return redirect_profile(self.request)


class FormFormsetView(TemplateView):
    def get_initial(self):
        return {}

    def get_initial_formset(self):
        return []

    def get_form_kwargs(self):
        kwargs = {
            'initial': self.get_initial(),
        }
        if self.request.method == 'POST':
            kwargs['data'] = self.request.POST
        return kwargs

    def get_form(self):
        return self.form_class(**self.get_form_kwargs())

    def get_formset_kwargs(self):
        kwargs = {
            'form_kwargs': self.get_formset_form_kwargs(),
        }
        if self.request.method == 'POST':
            kwargs['data'] = self.request.POST
        else:
            kwargs['initial'] = self.get_initial_formset()
        return kwargs

    def get_formset_form_kwargs(self):
        return {}

    def get_formset(self):
        Formset = formset_factory(
            self.formset_form_class, formset=self.formset_class, extra=2)
        return Formset(**self.get_formset_kwargs())

    def get_context_data(self, **kwargs):
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        if 'formset' not in kwargs:
            kwargs['formset'] = self.get_formset()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        formset = self.get_formset()
        if form.is_valid() and formset.is_valid():
            return self.forms_valid(form, formset)
        else:
            return self.forms_invalid(form, formset)

    def forms_valid(self, form, formset):
        return HttpResponseRedirect(self.get_success_url())

    def forms_invalid(self, form, formset):
        return self.render_to_response(
            self.get_context_data(form=form, formset=formset))


class InvoiceCombine(LoginRequiredMixin, FormFormsetView):
    template_name = 'invoices/combine.html'
    form_class = CombineForm
    formset_form_class = InvoiceForm
    formset_class = InvoiceFormset

    def get_initial(self):
        user = self.request.user
        initial = {
            'invoiced_entity': user.userprofile.display_name()
        }
        try:
            attendee = user.attendee
        except Attendee.DoesNotExist:
            pass
        else:
            initial['billing_address'] = attendee.billing_address
        return initial

    def get_initial_formset(self):
        return [{'url': url}
                for i, url in enumerate(self.request.GET.getlist('invoice'))]

    def get_formset_form_kwargs(self):
        return {
            'user': self.request.user,
        }

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def forms_valid(self, form, formset):
        user = self.request.user

        invoice = Invoice(
            recipient=user,
            status='new',
            compound=True,
            date=timezone.now(),
            invoiced_entity=form.cleaned_data['invoiced_entity'],
            billing_address=form.cleaned_data['billing_address'],
        )
        invoice.save()

        for i, form in enumerate(formset.forms):
            if not hasattr(form, 'invoice'):
                continue
            child_invoice = form.invoice
            InvoiceLine(
                invoice_id=invoice.id,
                line_order=i,
                reference='INV#{}'.format(child_invoice.reference_number),
                description='DebConf attendance for {}'.format(
                    child_invoice.recipient.userprofile.display_name()
                ),
                unit_price=child_invoice.total,
                quantity=1,
            ).save()

        self.reference_number = invoice.reference_number
        return super().forms_valid(form, formset)

    def get_success_url(self):
        return reverse('invoices:display',
                       kwargs={'reference_number': self.reference_number})


@csrf_exempt
def stripe_webhook(request):
    sig_header = request.META.get('HTTP_STRIPE_SIGNATURE')
    try:
        event = Webhook.construct_event(
            request.body, sig_header, settings.STRIPE_ENDPOINT_SECRET)
    except ValueError:
        return HttpResponseBadRequest("Invalid event")
    except SignatureVerificationError:
        return HttpResponse(status=400)
    if event.type == 'payment_intent.succeeded':
        intent = event.data.object
        payment_intent_succeeded(intent, ignore_unrelated=True)
    elif event.type == 'charge.dispute.created':
        dispute = event.data.object
        dispute_filed(dispute, ignore_unrelated=True)
    elif event.type == 'charge.refunded':
        charge = event.data.object
        charge_refunded(charge, ignore_unrelated=True)
    else:
        return HttpResponse(status=400)
    return HttpResponse(status=204)

invoices/templates/invoices/combine.html
{% extends 'wafer/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <h1>Combine Invoices</h1>
  <p>
    You can combine invoices from multiple attendees (including yourself, if
    desired) into a single invoice, to be paid together.
    To do this, you need the <b>shared</b> URL for each invoice.
  </p>
  <h2>Invoices to be combined:</h2>
  <form method="post">
    {% crispy form %}
    <div id="formset">
      {% crispy formset formset.form.helper %}
    </div>
    <input class="btn btn-info" type="button" value="Add Another Invoice" id="add-url">
    <input class="btn btn-primary" type="submit" name="submit"
           value="Generate Combined Invoice">
  </form>
{% endblock %}
{% block extra_foot %}
<script type="text/javascript">
  'use strict';
  $(function() {
    $('#add-url').on('click', function(e) {
      var forms = parseInt($('#id_form-TOTAL_FORMS').val());

      var new_name = 'form-' + forms + '-url';

      var form = $('#div_id_form-0-url').clone();
      form.attr('id', 'div_id_' + new_name);

      form.find('label').attr('for', '#id_' + new_name);

      var input = form.find('input');
      input.attr('id', 'id_' + new_name);
      input.attr('name', new_name);
      input.val('');

      form.appendTo('#formset');

      $('#id_form-TOTAL_FORMS').val(forms + 1);
    });
  });
</script>
{% endblock %}

invoices/templates/invoices/invoice_detail.html
{% extends "wafer/base.html" %}
{% block title %}{{ WAFER_CONFERENCE_NAME }} - Invoice {{ object.reference_number }}{% endblock %}
{% block content %}
{% include 'invoices/includes/invoice.html' %}
<div class="row d-print-none">
  <div class="col-md">
    {% if object.status == 'new' %}
      {% if not using_signed_url %}
        <div class="card border-info mb-3">
          <h4 class="card-header bg-info">Forward Invoice:</h4>
          <div class="card-body">
            Is somebody else going to pay this on your behalf?<br>
            Send them
            <a href="{{ object.get_signed_url }}">this URL
              <i class="fas fa-link"></i></a>.<br>
            They will be able to combine this with other invoices, and pay them in
            a single payment, if desired.
          </div>
        </div>
        <div class="card border-danger mb-3">
          <h4 class="card-header bg-danger">Danger Zone:</h4>
          <div class="card-body">
            <p>
              If you have modified your registration and the invoice is no longer
              correct, you may cancel it and re-create it.
            </p>
            <form action={% url 'invoices:cancel' reference_number=object.reference_number %} method="post">
              {% csrf_token %}
              <input type="submit" class="btn btn-warning" value="Cancel Invoice">
            </form>
          </div>
        </div>
      {% elif not object.compound %}
        <div class="card border-info mb-3">
          <h4 class="card-header bg-info">Combine Invoices:</h4>
          <div class="card-body">
            <p>
              If you want to pay for multiple invoices, together, you can combine
              them into a single invoice.
            </p>
            <a href="{% url 'invoices:combine' %}?invoice={{ view.request.build_absolute_uri|urlencode }}"
               class="btn btn-warning">Combine Invoices</a>
          </div>
        </div>
      {% endif %}
    {% endif %}
  </div>
  <div class="col-md">
    {% if object.status == 'canceled' %}
      <div class="card border-danger mb-3">
        <h4 class="card-header bg-danger">Cancelled!</h4>
        <div class="card-body">
          <p>Cancelled on {{ object.last_update | date }}</p>
        </div>
      </div>
    {% elif object.status == 'disputed' %}
      <div class="card border-danger mb-3">
        <h4 class="card-header bg-danger">Payment Disputed!</h4>
        <div class="card-body">
          <p>Disputed on {{ object.last_update | date }}</p>
        </div>
      </div>
    {% elif object.status == 'refunded' %}
      <div class="card border-danger mb-3">
        <h4 class="card-header bg-danger">Payment Refunded</h4>
        <div class="card-body">
          <p>Refunded on {{ object.last_update | date }}</p>
        </div>
      </div>
    {% else %}
      <div class="card border-success mb-3">
        <h4 class="card-header bg-success">Payment:</h4>
        <div class="card-body">
          {% if object.status == 'new' %}
            <div id="card-form">
              <div id="card-element" class="pb-3">
                <div class="alert alert-danger">
                  This is where the Stripe Credit Card form is displayed.
                  <br>
                  {% if STRIPE_PUBLISHABLE_KEY %}
                    If you see this and use LibreJS, NoScript, Request Policy, or
                    some similar browser plugin, you may need to whitelist this
                    site or <code>js.stripe.com</code> in it.
                  {% else %}
                    Stripe integration is not configured.
                  {% endif %}
                </div>
              </div>
              <!-- Used to display Element errors. -->
              <div id="card-errors" role="alert"></div>
              <button id="submit-payment" class="btn btn-primary">Pay by Card</button>
            </div>
            <div id="payment-complete" class="alert alert-success" style="display: none">
              Payment processed, thank you!
            </div>
          {% elif object.status == 'pending' %}
            <p>Waiting for payment confirmation</p>
          {% elif object.status == 'paid' %}
            <p>
              Payment received on {{ object.last_update | date }} <br>
              Transaction number {{ object.transaction_id }}
            </p>
          {% endif %}
        </div>
      </div>
    {% endif %}
    <div class="mb-3 text-right">
      <a class="btn btn-warning print-button" href="">Print</a>
    </div>
  </div>
</div>
{% endblock %}
{% block extra_foot %}
  {% if object.status == 'new' and STRIPE_PUBLISHABLE_KEY %}
    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
      $(function() {
        var stripe = Stripe('{{ STRIPE_PUBLISHABLE_KEY }}');
        var lang = document.querySelector('html').getAttribute('lang') || 'en';
        var elements = stripe.elements({locale: lang});
        var style = {
          base: {
            fontSize: '18px',
          }
        };
        var card = elements.create('card', {style: style});
        var submitButton = $('#submit-payment');
        card.mount('#card-element');


        var displayError = function(message) {
          const tag = $('#card-errors');
          tag.text(message);
          if (message) {
            tag.addClass('alert alert-warning');
          } else {
            tag.removeClass('alert alert-warning');
            submitButton.removeAttr('disabled');
          }
        };

        card.addEventListener('change', ({error}) => {
          if (error) {
            displayError(error.message);
          } else {
            displayError('');
          }
        });

        submitButton.click(function(ev) {
          submitButton.attr('disabled', 'disabled');
          stripe.confirmCardPayment('{{ payment_intent_client_secret }}', {
            payment_method: {card: card}
          }).then(function(result) {
            if (result.error) {
              displayError(result.error.message);
            } else {
              if (result.paymentIntent.status === 'succeeded') {
                $('#card-form').hide();
                $('#payment-complete').show();
              }
            }
          });
        });
      });
    </script>
  {% endif %}
  <script type="text/javascript">
    $(function() {
      $('.print-button').click(function() {
        window.print();
      });
    });
  </script>
{% endblock %}